services:
  db:
    image: postgres:16
    env_file:
      - .env
    container_name: teamfinder_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  web:
    build: .
    env_file:
      - .env
    container_name: teamfinder_web
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: unless-stopped

volumes:
  postgres_data:
